name: Build Patient Service (Maven + Docker)

on:
  push:
    branches: [ main ]
    paths:
      - "patient-service/**"

jobs:
  build:
    runs-on: self-hosted

    env:
      IMAGE_NAME: 12345678.dkr.ecr.us-east-1.amazonaws.com/patient-service:latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -f patient-service/pom.xml clean package -DskipTests

      - name: Docker Version
        run: docker --version

      - name: Build Docker Image
        run: |
          sudo docker build -t $IMAGE_NAME patient-service
          echo "Docker image $IMAGE_NAME built successfully"

      - name: Cleanup disk space
        run: |
          sudo rm -rf /home/ubuntu/actions-runner/_work/*

